server:
  port: 8808
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 如果mysql数据版本是5.x以上末尾加上 ?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    url: jdbc:mysql://47.115.22.7:3306/my_blog
    username: root
    password: zhou@11043
  jackson:
    date-format: yyyy-MM-dd
  redis:
    host: 47.115.22.7
    port: 6379
#  thymeleaf:
#    prefix: classpath:/templates/
#  thymeleaf:
#    cache: false

logging:
  level:
    com.zca.blog: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
